apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: app-namespace
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: 200Mi
    limits.cpu: "400m"
    limits.memory: 400Mi

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app-namespace
spec:
  selector:
    matchLabels:
      run: my-nginx-3
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx-3
    spec:
      containers:
      - name: my-nginx
        image: nginx
        resources:
          requests:
             cpu: 100m
             memory: 100Mi
          limits:
             cpu: 200m
             memory: 200Mi
        ports:
        - containerPort: 80
