apiVersion: v1
kind: Service
metadata:
    name: my-nginx-svc
    labels:
      run: my-nginx-3
spec:
   ports:
   - port: 80
     protocol: TCP
     targetPort: 80
   type: NodePort
   selector:
      run: my-nginx-3
