apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      run: my-nginx-3
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx-3
    spec:
      containers:
      - name: my-nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
             cpu: 100m
             memory: 100Mi
          limits:
             cpu: 300m
             memory: 300Mi
        ports:
        - containerPort: 80
